### ISSUE TITLE
Is opening .oni supported?

### ISSUE THREAD

**Issue by Leon99** [falahati/NiWrapper.Net#20]
It doesn't seem like the wrapper allows to call Device.open with a custom URI.

**Comment by falahati** [comment]
Hey,

I think it does. Please check again.

**Comment by Leon99** [comment]
Thanks, I've found it already.
On 5 May 2017, at 07:12, Soroush <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey,

I think it does. Please check again.
