### ISSUE TITLE
NuGet - NiWrapper.dll Not Found

### ISSUE THREAD

**Issue by ve4cib** [falahati/NiWrapper.Net#21]
This is probably not actually an NiWrapper issue, but it might be, so I'm posting here to hopefully get some help.

I have an application made using NiWrapper for x64 that crashes when trying to initialize OpenNI.  The error I'm getting is "Unable to load NiWrapper.dll" as soon as I call OpenNI.Initialize().  I have installed the library with NuGet, and the DLL in question is located inside the same directory as the application.  (See screenshots below of the error message in Visual studio + the code that's crashing, contents of the executable directory, and my installed NuGet packages).

The machine in question is running Win10 x64, fully-updated, and freshly reformatted and reinstalled last week.  The code compiles without error, it's just when I try to run the program that it crashes on the OpenNI.Initialize() call.

Replicating the problem is trivial: I simply create a new project, install NiWrapper via NuGet, and put OpenNI.Initialize() inside main and the error happens (on that one machine).  Curiously, the exact same code runs on other computers I've tested on, which is why I'm skeptical that this is specifically an issue with NiWrapper.  But NiWrapper seems to be the only dll that the system is having trouble with, so I'm really not sure.

I have tried copying a working build from another computer onto the one I'm encountering problems on, and get the same result. Installing Visual Studio, reinstalling NiWrapper via NuGet, and recompiling directly on the test machine also results in the exact same error.

Screenshots:
Error message + code in main that's crashing: https://www.dropbox.com/s/bsjoboie4s8sf50/err.png?dl=0

Contents of the application directory: https://www.dropbox.com/s/1be9qwkfayjcp0q/dir.png?dl=0

Installed NuGet packages: https://www.dropbox.com/s/4fg0gqaggj5vvmc/nuget.png?dl=0

Thanks a lot for any insight/assistance you can offer. If you need more information please let me know and I'll provide whatever you need.

**Comment by falahati** [comment]
Hi,

Please try installing following packages on the problematic system and report back.

- https://www.microsoft.com/en-us/download/details.aspx?id=14632
- https://www.microsoft.com/en-us/download/details.aspx?id=5555

If 'dll' is right there but program still can't finds it, probably there is a problem with one of its dependencies. And NiWrapper.dll is only dependent to OpenNI2.dll, MSVC100.dll and Kernel32.dll, so it is a valid guess to think that you might have missed the "Microsoft Visual C++ 2010 Redistributable Package".

**Comment by ve4cib** [comment]
Fantastic! Thank-you. I had installed the VC++ 2015 redistributable package, but hadn't thought to install the 2010 one as well.  That seems to have solved the problem.

Thank-you very much!

**Comment by falahati** [comment]
Glad to hear

Yeah the project is compiled with VS2010 and thereforce used the VCR2010 components. This is also the reason that you need to update the "BaseClass.Contrib.Nuget.Output" NuGet package when working with VS2015.
